[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcutil"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.11"

[[constraint]]
  name = "github.com/gorilla/rpc"
  version = "1.1.0"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
  version = "0.6.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/soheilhy/cmux"
  version = "0.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/tyler-smith/go-bip39"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.2"

[prune]
  go-tests = true


[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"
